### ISSUE TITLE
SchedTaskT won't compile on PlatformIO

### ISSUE THREAD

**Issue by epageler** [Nospampls/SchedTask#5]
I watched your YouTube videos & have been testing your examples. I really want to use SchedTaskT on one of my projects.

Unfortunately, your Example 4, uses SchedTaskT won't complle on PlatformIO. It compiles just fine on the Arduino IDE. I much prefer to PlatformIO to the Arduino IDE.  I'm using the Adafruit ESP32 board. BTW, SchedTask compiles with no errors. 

I'll continue to watch your Gitbhub site for updates.  Keep up the good work!

**Comment by Nospampls** [comment]
Are you using the latest version, 1.1.0?  I was able to compile Example_4 on PlatformIO with this version.

Thanks.

**Comment by epageler** [comment]
Yes, I was using V1.1.0.

**Comment by Nospampls** [comment]
I was able to compile Example_4  using PlatformIO, which I had never used
before this test.  Can you give me more specifics on the failure?

**Comment by epageler** [comment]
Here is the output from the compile:

Processing featheresp32 (platform: espressif32; board: featheresp32; framework: arduino)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/featheresp32.html
PLATFORM: Espressif 32 (2.0.0) > Adafruit ESP32 Feather
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 3.10004.200129 (1.0.4)
 - tool-esptoolpy 1.20600.0 (2.6.0)
 - toolchain-xtensa32 2.50200.80 (5.2.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 27 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <SchedTask> 1.1.0
Building in release mode
Compiling .pio\build\featheresp32\src\main.cpp.o
Archiving .pio\build\featheresp32\lib67b\libSchedTask.a
Compiling .pio\build\featheresp32\FrameworkArduino\HardwareSerial.cpp.o
Compiling .pio\build\featheresp32\FrameworkArduino\IPAddress.cpp.o
Compiling .pio\build\featheresp32\FrameworkArduino\IPv6Address.cpp.o
In file included from .pio\libdeps\featheresp32\SchedTask\src/SchedTaskT.h:358:0,
                 from src\main.cpp:24:
.pio\libdeps\featheresp32\SchedTask\src/SchedBase.h: In member function 'virtual bool SchedBase::checkFunc()':
.pio\libdeps\featheresp32\SchedTask\src/SchedBase.h:76:30: warning: no return statement in function returning non-void [-Wreturn-type]
   virtual bool checkFunc() {;}         // whether func is non-NULL
                              ^
In file included from src\main.cpp:24:0:
.pio\libdeps\featheresp32\SchedTask\src/SchedTaskT.h: In member function 'void (* SchedTaskT<T>::getFunc())()':
.pio\libdeps\featheresp32\SchedTask\src/SchedTaskT.h:388:21: warning: no return statement in function returning non-void [-Wreturn-type]
   pFunc getFunc() {;}             // overrides pure virtual in base so this class not abstract
                     ^
.pio\libdeps\featheresp32\SchedTask\src/SchedTaskT.h: In instantiation of 'SchedTaskT<T>::SchedTaskT(long unsigned int, long unsigned int, SchedTaskT<T>::pFuncT, T) [with T = int; SchedTaskT<T>::pFuncT = void (*)(int)]':
src\main.cpp:34:59:   required from here
.pio\libdeps\featheresp32\SchedTask\src/SchedTaskT.h:385:10: error: 'SchedTaskT<int>::func' will be initialized after [-Werror=reorder]
   pFuncT func;              // address of function to call with parameter of type T
          ^
.pio\libdeps\featheresp32\SchedTask\src/SchedTaskT.h:384:5: error:   'int SchedTaskT<int>::parm' [-Werror=reorder]
   T parm;                // parameter of type T to be passed to dispatched task
     ^
.pio\libdeps\featheresp32\SchedTask\src/SchedTaskT.h:397:23: error:   when initialized here [-Werror=reorder]
 template <typename T> SchedTaskT<T>::SchedTaskT (unsigned long nxt, unsigned long intval, pFuncT pFnc, T arg) : SchedBase(nxt, intval), func(pFnc), parm(arg) {} // constructor template
                       ^
cc1plus.exe: some warnings being treated as errors
Compiling .pio\build\featheresp32\FrameworkArduino\MD5Builder.cpp.o
*** [.pio\build\featheresp32\src\main.cpp.o] Error 1
===================================================================== [FAILED] Took 10.12 seconds =====================================================================

**Comment by Nospampls** [comment]
Thanks.  I have pushed version 1.1.1.  It may take a day or so to be
released.  But you can download now from Github at
https://github.com/Nospampls/SchedTask

Please let me know if this resolves the issues.
